---
title: "Lab 00 - Hello IDS!"
author: "Daisy Haylock"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Anna", "Michelle", "Mariam", 
           "Adam"),
  github_username = c("annahouston", "cherryshelley", "jivamariam", 
                     "adamcarroll1"), 
  colour = c("darkorchid1", "mistyrose", "darkred",
             "darkslategray1"),
  hobby = c("netball", "crocheting", "baking", 
            "rugby"),
  favourite_number = c(7, 8, 5, 2)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```

The plot shows a bar graph of each person's favourite number with each bar coloured their favourite colour.
